imports:
    - { resource: tables.yml }

services:
    paul999.tfa.sessionHelper:
        class: paul999\tfa\helper\session_helper
        arguments:
            - @dbal.conn
            - @config
            - @user
            - @paul999.tfa.module_collection
            - %paul999.2fa.tables.tfa_registration%
            - %tables.users%

    paul999.tfa.module_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: paul999.tfa.module }

    paul999.tfa.controller:
        class: paul999\tfa\controller\main_controller
        arguments:
            - @controller.helper
            - @dbal.conn
            - @template
            - @user
            - @request
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.users%
            - %paul999.2fa.tables.tfa_registration%

    paul999.tfa.listener:
        class: paul999\tfa\event\listener
        arguments:
            - @paul999.tfa.sessionHelper
            - @controller.helper
            - @user
            - @request
            - @dbal.conn
            - @config
            - %core.php_ext%
            - %core.root_path%
        tags:
            - { name: event.listener }

