imports:
    - { resource: tables.yml }

services:
    paul999.tfa.sessionHelper:
        class: paul999\tfa\helper\sessionHelper

    paul999.tfa.controller:
        class: paul999\tfa\controller\main_controller
        arguments:
            - @controller.helper
            - @dbal.conn
            - @template
            - @user
            - @request
            - %core.root_path%
            - %core.php_ext%
            - %tables.users%
            - %paul999.2fa.tables.tfa_registration%

    paul999.tfa.listener:
        class: paul999\tfa\event\listener
        arguments:
            - @paul999.tfa.sessionHelper
            - @controller.helper
        tags:
            - { name: event.listener }

